### ISSUE TITLE
Consumer, Kinesis and DynamoDB client configs

### ISSUE THREAD

**Issue by mulloymorrow** [code-monastery/dropwizard-kinesis#4]
Will the region for the DynamoDB and Kinesis clients ever be different? Seems these should be coupled, e.g. DynamoDB client should inherit Kinesis Client configs.

**Comment by randyp** [comment]
was trying to do the most generic thing possible, where one could theoretically even use different credentials for kinesis/dynamodb clients.

let's revisit this issue if more people than us use this library.

**Comment by mulloymorrow** [comment]
sounds good. just started using this for cross account access. kinesis stream in one account. consumer in another account. Would make sense to checkpoint in my AWS account's dynamoDB while consuming from the other account. In which case, would need separate credentials for each client. We can close this.
